<template>
    <TableTree
        :data="data"
        :title-master="'text'"
        :title-label="['type']"
        :smallestUnit="'device'"
        @getCheckedList="checkedUpList"
    />
</template>

<script>
import TableTree from './components/tableTree.vue'
import axios from 'axios'
import { reactive } from 'vue'
export default {
    components: {
        TableTree,
    },
    setup() {
        const list = reactive({})
        const checkedUpList = (data) => {
            console.log('這是來自子組件的資料', data)
        }
        const data = reactive([
            {
                id: 2,
                text: 'Fac7',
                children: [
                    {
                        id: 1,
                        text: 'GAS_L30',
                        children: [
                            {
                                id: 5,
                                text: 'DTR-105AA',
                                children: [],
                                type: 'device',
                                _XID: 'row_9',
                            },
                            {
                                id: 8,
                                text: 'DTR-105AB',
                                children: [],
                                type: 'device',
                                _XID: 'row_10',
                            },
                            {
                                id: 72,
                                text: 'DTR-105AD',
                                children: [],
                                type: 'device',
                                _XID: 'row_11',
                            },
                            {
                                id: 80,
                                text: 'DTR-105AE',
                                children: [],
                                type: 'device',
                                _XID: 'row_12',
                            },
                            {
                                id: 82,
                                text: 'DTR-105AG',
                                children: [],
                                type: 'device',
                                _XID: 'row_13',
                            },
                            {
                                id: 1,
                                text: 'DTR-105BA',
                                children: [],
                                type: 'device',
                                _XID: 'row_14',
                            },
                            {
                                id: 24,
                                text: 'DTR-105BB',
                                children: [],
                                type: 'device',
                                _XID: 'row_15',
                            },
                            {
                                id: 88,
                                text: 'DTR-105BC',
                                children: [],
                                type: 'device',
                                _XID: 'row_16',
                            },
                            {
                                id: 4,
                                text: 'DTR-105BD',
                                children: [],
                                type: 'device',
                                _XID: 'row_17',
                            },
                            {
                                id: 84,
                                text: 'DTR-105BE',
                                children: [],
                                type: 'device',
                                _XID: 'row_18',
                            },
                            {
                                id: 9,
                                text: 'DTR-105BF',
                                children: [],
                                type: 'device',
                                _XID: 'row_19',
                            },
                            {
                                id: 6,
                                text: 'DTR-305AA',
                                children: [],
                                type: 'device',
                                _XID: 'row_20',
                            },
                            {
                                id: 7,
                                text: 'DTR-305AB',
                                children: [],
                                type: 'device',
                                _XID: 'row_21',
                            },
                            {
                                id: 71,
                                text: 'DTR-305AD',
                                children: [],
                                type: 'device',
                                _XID: 'row_22',
                            },
                            {
                                id: 81,
                                text: 'DTR-305AE',
                                children: [],
                                type: 'device',
                                _XID: 'row_23',
                            },
                            {
                                id: 83,
                                text: 'DTR-305AG',
                                children: [],
                                type: 'device',
                                _XID: 'row_24',
                            },
                            {
                                id: 2,
                                text: 'DTR-305BA',
                                children: [],
                                type: 'device',
                                _XID: 'row_25',
                            },
                            {
                                id: 23,
                                text: 'DTR-305BB',
                                children: [],
                                type: 'device',
                                _XID: 'row_26',
                            },
                            {
                                id: 89,
                                text: 'DTR-305BC',
                                children: [],
                                type: 'device',
                                _XID: 'row_27',
                            },
                            {
                                id: 3,
                                text: 'DTR-305BD',
                                children: [],
                                type: 'device',
                                _XID: 'row_28',
                            },
                            {
                                id: 85,
                                text: 'DTR-305BE',
                                children: [],
                                type: 'device',
                                _XID: 'row_29',
                            },
                            {
                                id: 10,
                                text: 'DTR-305BF',
                                children: [],
                                type: 'device',
                                _XID: 'row_30',
                            },
                            {
                                id: 87,
                                text: 'EDTR-203DAA',
                                children: [],
                                type: 'device',
                                _XID: 'row_31',
                            },
                            {
                                id: 12,
                                text: 'EDTR-203DAC',
                                children: [],
                                type: 'device',
                                _XID: 'row_32',
                            },
                            {
                                id: 86,
                                text: 'EDTR-303DAA',
                                children: [],
                                type: 'device',
                                _XID: 'row_33',
                            },
                            {
                                id: 11,
                                text: 'EDTR-303DAC',
                                children: [],
                                type: 'device',
                                _XID: 'row_34',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_8',
                    },
                    {
                        id: 2,
                        text: 'SUP_L10',
                        children: [
                            {
                                id: 16,
                                text: 'DTR-104B',
                                children: [],
                                type: 'device',
                                _XID: 'row_36',
                            },
                            {
                                id: 21,
                                text: 'DTR-104C',
                                children: [],
                                type: 'device',
                                _XID: 'row_37',
                            },
                            {
                                id: 18,
                                text: 'DTR-104D',
                                children: [],
                                type: 'device',
                                _XID: 'row_38',
                            },
                            {
                                id: 19,
                                text: 'DTR-104E',
                                children: [],
                                type: 'device',
                                _XID: 'row_39',
                            },
                            {
                                id: 15,
                                text: 'DTR-204B',
                                children: [],
                                type: 'device',
                                _XID: 'row_40',
                            },
                            {
                                id: 22,
                                text: 'DTR-204C',
                                children: [],
                                type: 'device',
                                _XID: 'row_41',
                            },
                            {
                                id: 17,
                                text: 'DTR-204D',
                                children: [],
                                type: 'device',
                                _XID: 'row_42',
                            },
                            {
                                id: 20,
                                text: 'DTR-204E',
                                children: [],
                                type: 'device',
                                _XID: 'row_43',
                            },
                            {
                                id: 14,
                                text: 'EDTR-203BA',
                                children: [],
                                type: 'device',
                                _XID: 'row_44',
                            },
                            {
                                id: 13,
                                text: 'EDTR-303BA',
                                children: [],
                                type: 'device',
                                _XID: 'row_45',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_35',
                    },
                    {
                        id: 3,
                        text: 'SUP_L35',
                        children: [
                            {
                                id: 33,
                                text: 'DTR-206D',
                                children: [],
                                type: 'device',
                                _XID: 'row_47',
                            },
                            {
                                id: 36,
                                text: 'DTR-206E',
                                children: [],
                                type: 'device',
                                _XID: 'row_48',
                            },
                            {
                                id: 37,
                                text: 'DTR-206F',
                                children: [],
                                type: 'device',
                                _XID: 'row_49',
                            },
                            {
                                id: 30,
                                text: 'DTR-206G',
                                children: [],
                                type: 'device',
                                _XID: 'row_50',
                            },
                            {
                                id: 31,
                                text: 'DTR-206H',
                                children: [],
                                type: 'device',
                                _XID: 'row_51',
                            },
                            {
                                id: 34,
                                text: 'DTR-306D',
                                children: [],
                                type: 'device',
                                _XID: 'row_52',
                            },
                            {
                                id: 35,
                                text: 'DTR-306E',
                                children: [],
                                type: 'device',
                                _XID: 'row_53',
                            },
                            {
                                id: 38,
                                text: 'DTR-306F',
                                children: [],
                                type: 'device',
                                _XID: 'row_54',
                            },
                            {
                                id: 29,
                                text: 'DTR-306G',
                                children: [],
                                type: 'device',
                                _XID: 'row_55',
                            },
                            {
                                id: 32,
                                text: 'DTR-306H',
                                children: [],
                                type: 'device',
                                _XID: 'row_56',
                            },
                            {
                                id: 26,
                                text: 'EDTR-203CA',
                                children: [],
                                type: 'device',
                                _XID: 'row_57',
                            },
                            {
                                id: 28,
                                text: 'EDTR-203CE',
                                children: [],
                                type: 'device',
                                _XID: 'row_58',
                            },
                            {
                                id: 25,
                                text: 'EDTR-303CA',
                                children: [],
                                type: 'device',
                                _XID: 'row_59',
                            },
                            {
                                id: 27,
                                text: 'EDTR-303CE',
                                children: [],
                                type: 'device',
                                _XID: 'row_60',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_46',
                    },
                    {
                        id: 4,
                        text: 'SUP_L30',
                        children: [
                            {
                                id: 48,
                                text: 'DTR-206AA',
                                children: [],
                                type: 'device',
                                _XID: 'row_62',
                            },
                            {
                                id: 41,
                                text: 'DTR-206AB',
                                children: [],
                                type: 'device',
                                _XID: 'row_63',
                            },
                            {
                                id: 40,
                                text: 'DTR-206AC',
                                children: [],
                                type: 'device',
                                _XID: 'row_64',
                            },
                            {
                                id: 50,
                                text: 'DTR-206AD',
                                children: [],
                                type: 'device',
                                _XID: 'row_65',
                            },
                            {
                                id: 43,
                                text: 'DTR-206AE',
                                children: [],
                                type: 'device',
                                _XID: 'row_66',
                            },
                            {
                                id: 47,
                                text: 'DTR-306AA',
                                children: [],
                                type: 'device',
                                _XID: 'row_67',
                            },
                            {
                                id: 42,
                                text: 'DTR-306AB',
                                children: [],
                                type: 'device',
                                _XID: 'row_68',
                            },
                            {
                                id: 39,
                                text: 'DTR-306AC',
                                children: [],
                                type: 'device',
                                _XID: 'row_69',
                            },
                            {
                                id: 49,
                                text: 'DTR-306AD',
                                children: [],
                                type: 'device',
                                _XID: 'row_70',
                            },
                            {
                                id: 44,
                                text: 'DTR-306AE',
                                children: [],
                                type: 'device',
                                _XID: 'row_71',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_61',
                    },
                    {
                        id: 5,
                        text: 'SUP_L25',
                        children: [
                            {
                                id: 53,
                                text: 'DTR-104AA',
                                children: [],
                                type: 'device',
                                _XID: 'row_73',
                            },
                            {
                                id: 56,
                                text: 'DTR-104AB',
                                children: [],
                                type: 'device',
                                _XID: 'row_74',
                            },
                            {
                                id: 59,
                                text: 'DTR-104AC',
                                children: [],
                                type: 'device',
                                _XID: 'row_75',
                            },
                            {
                                id: 51,
                                text: 'DTR-104AD',
                                children: [],
                                type: 'device',
                                _XID: 'row_76',
                            },
                            {
                                id: 58,
                                text: 'DTR-104AE',
                                children: [],
                                type: 'device',
                                _XID: 'row_77',
                            },
                            {
                                id: 54,
                                text: 'DTR-204AA',
                                children: [],
                                type: 'device',
                                _XID: 'row_78',
                            },
                            {
                                id: 55,
                                text: 'DTR-204AB',
                                children: [],
                                type: 'device',
                                _XID: 'row_79',
                            },
                            {
                                id: 60,
                                text: 'DTR-204AC',
                                children: [],
                                type: 'device',
                                _XID: 'row_80',
                            },
                            {
                                id: 52,
                                text: 'DTR-204AD',
                                children: [],
                                type: 'device',
                                _XID: 'row_81',
                            },
                            {
                                id: 57,
                                text: 'DTR-204AE',
                                children: [],
                                type: 'device',
                                _XID: 'row_82',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_72',
                    },
                    {
                        id: 6,
                        text: 'PSS_GIS',
                        children: [
                            {
                                id: 63,
                                text: 'BUS-1',
                                children: [],
                                type: 'device',
                                _XID: 'row_84',
                            },
                            {
                                id: 64,
                                text: 'BUS-2',
                                children: [],
                                type: 'device',
                                _XID: 'row_85',
                            },
                            {
                                id: 65,
                                text: 'BUS-3',
                                children: [],
                                type: 'device',
                                _XID: 'row_86',
                            },
                            {
                                id: 66,
                                text: 'BUS-4',
                                children: [],
                                type: 'device',
                                _XID: 'row_87',
                            },
                            {
                                id: 67,
                                text: 'BUS-5',
                                children: [],
                                type: 'device',
                                _XID: 'row_88',
                            },
                            {
                                id: 68,
                                text: 'BUS-6',
                                children: [],
                                type: 'device',
                                _XID: 'row_89',
                            },
                            {
                                id: 61,
                                text: 'GIS-1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_90',
                            },
                            {
                                id: 62,
                                text: 'GIS-2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_91',
                            },
                            {
                                id: 73,
                                text: 'GIS-TR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_92',
                            },
                            {
                                id: 70,
                                text: 'GIS-TR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_93',
                            },
                            {
                                id: 69,
                                text: 'GIS-TR3-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_94',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_83',
                    },
                    {
                        id: 7,
                        text: 'PSS_MTR',
                        children: [
                            {
                                id: 78,
                                text: 'MTR1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_96',
                            },
                            {
                                id: 79,
                                text: 'MTR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_97',
                            },
                            {
                                id: 76,
                                text: 'MTR2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_98',
                            },
                            {
                                id: 77,
                                text: 'MTR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_99',
                            },
                            {
                                id: 74,
                                text: 'MTR3-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_100',
                            },
                            {
                                id: 75,
                                text: 'MTR3-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_101',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_95',
                    },
                    {
                        id: 21,
                        text: 'GAS_L20',
                        children: [
                            {
                                id: 46,
                                text: '#01',
                                children: [],
                                type: 'device',
                                _XID: 'row_103',
                            },
                            {
                                id: 45,
                                text: '#02',
                                children: [],
                                type: 'device',
                                _XID: 'row_104',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_102',
                    },
                ],
                type: 'customer',
                _XID: 'row_7',
            },
            {
                id: 3,
                text: 'Fac4',
                children: [
                    {
                        id: 8,
                        text: 'PSS_GIS',
                        children: [
                            {
                                id: 92,
                                text: 'BUS-1',
                                children: [],
                                type: 'device',
                                _XID: 'row_107',
                            },
                            {
                                id: 93,
                                text: 'BUS-2',
                                children: [],
                                type: 'device',
                                _XID: 'row_108',
                            },
                            {
                                id: 94,
                                text: 'BUS-3',
                                children: [],
                                type: 'device',
                                _XID: 'row_109',
                            },
                            {
                                id: 95,
                                text: 'BUS-4',
                                children: [],
                                type: 'device',
                                _XID: 'row_110',
                            },
                            {
                                id: 96,
                                text: 'BUS-5',
                                children: [],
                                type: 'device',
                                _XID: 'row_111',
                            },
                            {
                                id: 97,
                                text: 'BUS-6',
                                children: [],
                                type: 'device',
                                _XID: 'row_112',
                            },
                            {
                                id: 98,
                                text: 'GIS-F01-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_113',
                            },
                            {
                                id: 99,
                                text: 'GIS-F02-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_114',
                            },
                            {
                                id: 100,
                                text: 'GIS-F03-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_115',
                            },
                            {
                                id: 90,
                                text: 'GIS-IN01-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_116',
                            },
                            {
                                id: 91,
                                text: 'GIS-IN02-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_117',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_106',
                    },
                    {
                        id: 9,
                        text: 'PSS_MTR',
                        children: [
                            {
                                id: 101,
                                text: 'MTR1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_119',
                            },
                            {
                                id: 102,
                                text: 'MTR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_120',
                            },
                            {
                                id: 103,
                                text: 'MTR2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_121',
                            },
                            {
                                id: 104,
                                text: 'MTR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_122',
                            },
                            {
                                id: 105,
                                text: 'MTR3-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_123',
                            },
                            {
                                id: 106,
                                text: 'MTR3-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_124',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_118',
                    },
                ],
                type: 'customer',
                _XID: 'row_105',
            },
            {
                id: 4,
                text: 'Fac1',
                children: [
                    {
                        id: 10,
                        text: 'CUB-1F_GIS',
                        children: [
                            {
                                id: 109,
                                text: 'BUS-1',
                                children: [],
                                type: 'device',
                                _XID: 'row_127',
                            },
                            {
                                id: 110,
                                text: 'BUS-2',
                                children: [],
                                type: 'device',
                                _XID: 'row_128',
                            },
                            {
                                id: 111,
                                text: 'BUS-3',
                                children: [],
                                type: 'device',
                                _XID: 'row_129',
                            },
                            {
                                id: 112,
                                text: 'BUS-4',
                                children: [],
                                type: 'device',
                                _XID: 'row_130',
                            },
                            {
                                id: 113,
                                text: 'BUS-5',
                                children: [],
                                type: 'device',
                                _XID: 'row_131',
                            },
                            {
                                id: 107,
                                text: 'GIS-E01-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_132',
                            },
                            {
                                id: 108,
                                text: 'GIS-E02-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_133',
                            },
                            {
                                id: 114,
                                text: 'GIS-E03-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_134',
                            },
                            {
                                id: 115,
                                text: 'GIS-E04-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_135',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_126',
                    },
                    {
                        id: 11,
                        text: 'CUB-1F_MTR',
                        children: [
                            {
                                id: 116,
                                text: 'MTR1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_137',
                            },
                            {
                                id: 117,
                                text: 'MTR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_138',
                            },
                            {
                                id: 118,
                                text: 'MTR2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_139',
                            },
                            {
                                id: 119,
                                text: 'MTR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_140',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_136',
                    },
                ],
                type: 'customer',
                _XID: 'row_125',
            },
            {
                id: 5,
                text: 'Fac3',
                children: [
                    {
                        id: 12,
                        text: 'EGT_MainTR',
                        children: [
                            {
                                id: 122,
                                text: 'XTR-301-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_143',
                            },
                            {
                                id: 123,
                                text: 'XTR-301-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_144',
                            },
                            {
                                id: 120,
                                text: 'XTR-401-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_145',
                            },
                            {
                                id: 121,
                                text: 'XTR-401-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_146',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_142',
                    },
                ],
                type: 'customer',
                _XID: 'row_141',
            },
            {
                id: 6,
                text: 'Fac2',
                children: [
                    {
                        id: 13,
                        text: 'PSS_GIS_1F',
                        children: [
                            {
                                id: 124,
                                text: 'GIS-E03-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_149',
                            },
                            {
                                id: 125,
                                text: 'GIS-E04-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_150',
                            },
                            {
                                id: 126,
                                text: 'GIS-E05-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_151',
                            },
                            {
                                id: 127,
                                text: 'GIS-E06-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_152',
                            },
                            {
                                id: 128,
                                text: 'GIS-E08-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_153',
                            },
                            {
                                id: 129,
                                text: 'GIS-E09-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_154',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_148',
                    },
                    {
                        id: 14,
                        text: 'PSS_MTR_1F',
                        children: [
                            {
                                id: 130,
                                text: 'MTR1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_156',
                            },
                            {
                                id: 131,
                                text: 'MTR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_157',
                            },
                            {
                                id: 132,
                                text: 'MTR2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_158',
                            },
                            {
                                id: 133,
                                text: 'MTR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_159',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_155',
                    },
                ],
                type: 'customer',
                _XID: 'row_147',
            },
            {
                id: 7,
                text: 'Fac5',
                children: [
                    {
                        id: 15,
                        text: 'PSS_GIS',
                        children: [
                            {
                                id: 136,
                                text: 'GIS-1650',
                                children: [],
                                type: 'device',
                                _XID: 'row_162',
                            },
                            {
                                id: 137,
                                text: 'GIS-1660',
                                children: [],
                                type: 'device',
                                _XID: 'row_163',
                            },
                            {
                                id: 134,
                                text: 'GIS-IN01',
                                children: [],
                                type: 'device',
                                _XID: 'row_164',
                            },
                            {
                                id: 135,
                                text: 'GIS-IN02',
                                children: [],
                                type: 'device',
                                _XID: 'row_165',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_161',
                    },
                    {
                        id: 16,
                        text: 'PSS_MainTR',
                        children: [
                            {
                                id: 138,
                                text: 'XTR-501-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_167',
                            },
                            {
                                id: 139,
                                text: 'XTR-501-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_168',
                            },
                            {
                                id: 140,
                                text: 'XTR-601-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_169',
                            },
                            {
                                id: 141,
                                text: 'XTR-601-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_170',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_166',
                    },
                ],
                type: 'customer',
                _XID: 'row_160',
            },
            {
                id: 8,
                text: 'Fac6',
                children: [
                    {
                        id: 17,
                        text: 'MTR',
                        children: [
                            {
                                id: 144,
                                text: 'XTR-101-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_173',
                            },
                            {
                                id: 145,
                                text: 'XTR-101-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_174',
                            },
                            {
                                id: 142,
                                text: 'XTR-201-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_175',
                            },
                            {
                                id: 143,
                                text: 'XTR-201-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_176',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_172',
                    },
                    {
                        id: 18,
                        text: 'GIS',
                        children: [
                            {
                                id: 148,
                                text: 'GIS-1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_178',
                            },
                            {
                                id: 146,
                                text: 'GIS-1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_179',
                            },
                            {
                                id: 149,
                                text: 'GIS-2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_180',
                            },
                            {
                                id: 147,
                                text: 'GIS-2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_181',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_177',
                    },
                ],
                type: 'customer',
                _XID: 'row_171',
            },
            {
                id: 9,
                text: 'Fac8',
                children: [
                    {
                        id: 19,
                        text: 'GIS',
                        children: [
                            {
                                id: 154,
                                text: 'BUS-1',
                                children: [],
                                type: 'device',
                                _XID: 'row_184',
                            },
                            {
                                id: 155,
                                text: 'BUS-2',
                                children: [],
                                type: 'device',
                                _XID: 'row_185',
                            },
                            {
                                id: 156,
                                text: 'BUS-3',
                                children: [],
                                type: 'device',
                                _XID: 'row_186',
                            },
                            {
                                id: 157,
                                text: 'BUS-4',
                                children: [],
                                type: 'device',
                                _XID: 'row_187',
                            },
                            {
                                id: 158,
                                text: 'BUS-5',
                                children: [],
                                type: 'device',
                                _XID: 'row_188',
                            },
                            {
                                id: 159,
                                text: 'BUS-6',
                                children: [],
                                type: 'device',
                                _XID: 'row_189',
                            },
                            {
                                id: 150,
                                text: 'GIS-IN01-IN-1',
                                children: [],
                                type: 'device',
                                _XID: 'row_190',
                            },
                            {
                                id: 151,
                                text: 'GIS-IN01-IN-2',
                                children: [],
                                type: 'device',
                                _XID: 'row_191',
                            },
                            {
                                id: 152,
                                text: 'GIS-IN02-IN-1',
                                children: [],
                                type: 'device',
                                _XID: 'row_192',
                            },
                            {
                                id: 153,
                                text: 'GIS-IN02-IN-2',
                                children: [],
                                type: 'device',
                                _XID: 'row_193',
                            },
                            {
                                id: 160,
                                text: 'GIS-TR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_194',
                            },
                            {
                                id: 161,
                                text: 'GIS-TR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_195',
                            },
                            {
                                id: 162,
                                text: 'GIS-TR3-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_196',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_183',
                    },
                    {
                        id: 20,
                        text: 'MTR',
                        children: [
                            {
                                id: 163,
                                text: 'MTR1-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_198',
                            },
                            {
                                id: 164,
                                text: 'MTR1-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_199',
                            },
                            {
                                id: 165,
                                text: 'MTR2-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_200',
                            },
                            {
                                id: 166,
                                text: 'MTR2-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_201',
                            },
                            {
                                id: 167,
                                text: 'MTR3-IN',
                                children: [],
                                type: 'device',
                                _XID: 'row_202',
                            },
                            {
                                id: 168,
                                text: 'MTR3-OUT',
                                children: [],
                                type: 'device',
                                _XID: 'row_203',
                            },
                        ],
                        type: 'station',
                        _XID: 'row_197',
                    },
                ],
                type: 'customer',
                _XID: 'row_182',
            },
        ])
        return {
            checkedUpList,
            data,
        }
    },
}
</script>
